name: steady_weather_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # network handler!
  dio: ^5.4.3+1
  # app router!
  go_router: ^14.0.1
  # local storage!
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # state management!
  flutter_riverpod: ^2.5.1
  # utilities!
  intl: ^0.19.0
  location: ^6.0.1
  collection: ^1.18.0
  google_fonts: ^6.2.1
  json_annotation: ^4.9.0
  flutter_animate: ^4.5.0
  freezed_annotation: ^2.4.1
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # linters!
  custom_lint: ^0.6.4
  flutter_lints: ^3.0.0
  # generators!
  freezed: ^2.5.2
  build_runner: ^2.4.9
  riverpod_lint: ^2.3.10
  hive_generator: ^2.0.1
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
